
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local setmetatable = setmetatable
local pairs = pairs
local tinsert = table.insert

local function get_map_size(m)
    local n = 0
    for _ in pairs(m) do
        n = n + 1
    end
    return n
end

local enums =
{
}

local tables =
{
    { name='TbQuest', file='tbquest', mode='map', index='id', value_type='Quest' },
}

local function InitTypes(methods)
    local readBool = methods.readBool
    local readByte = methods.readByte
    local readShort = methods.readShort
    local readFshort = methods.readFshort
    local readInt = methods.readInt
    local readFint = methods.readFint
    local readLong = methods.readLong
    local readFlong = methods.readFlong
    local readFloat = methods.readFloat
    local readDouble = methods.readDouble
    local readSize = methods.readSize
    local readString = methods.readString

    local readList = methods.readList
    local readArray = methods.readArray or readList
    local readSet = methods.readSet
    local readMap = methods.readMap
    local readNullableBool = methods.readNullableBool

    local beans = {}
    do
    ---@class Quest
         ---@field public id integer
         ---@field public name string
         ---@field public rewards Reward[]
         ---@field public requirements table<integer, integer>
         ---@field public prerequisites integer[]

        local class = methods.getClass('Quest')
        class._id = 78391490
        class._type_ = 'Quest'
        local id2name = {  }
        class._deserialize = function(bs)
            local o = {
            id = readInt(bs),
            name = readString(bs),
            rewards = readArray(bs, beans['Reward']._deserialize),
            requirements = readMap(bs, readInt, readInt),
            prerequisites = readList(bs, readInt),
            }
            setmetatable(o, class)
            return o
        end
        beans[class._type_] = class
    end
    do
    ---@class Reward
         ---@field public id integer
         ---@field public amount integer

        local class = methods.getClass('Reward')
        class._id = -1850459313
        class._type_ = 'Reward'
        local id2name = {  }
        class._deserialize = function(bs)
            local o = {
            id = readInt(bs),
            amount = readInt(bs),
            }
            setmetatable(o, class)
            return o
        end
        beans[class._type_] = class
    end


    return { enums = enums, beans = beans, tables = tables }
    end

return { InitTypes = InitTypes }

