
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local setmetatable = setmetatable
local pairs = pairs
local tinsert = table.insert

local function get_map_size(m)
    local n = 0
    for _ in pairs(m) do
        n = n + 1
    end
    return n
end

local enums =
{
}

local tables =
{
    { name='TbSkill', file='tbskill', mode='map', index='id', value_type='SkillConfig' },
}

local function InitTypes(methods)
    local readList = methods.readList
    local readArray = methods.readArray or readList
    local readSet = methods.readSet
    local readMap = methods.readMap

    local beans = {}
    do
        local class = methods.getClass('EffectData')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['EffectData'] = class
    end
    do
        local class = methods.getClass('SkillConfig')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.effect = beans['EffectData']._deserialize(bs.effect)
            setmetatable(o, class)
            return o
        end
        beans['SkillConfig'] = class
    end


    return { enums = enums, beans = beans, tables = tables }
    end

return { InitTypes = InitTypes }


