
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local setmetatable = setmetatable
local pairs = pairs
local tinsert = table.insert

local function get_map_size(m)
    local n = 0
    for _ in pairs(m) do
        n = n + 1
    end
    return n
end

local enums =
{
}

local tables =
{
    { name='TbSkill', file='tbskill', mode='map', index='id', value_type='Skill' },
    { name='TbEnemy', file='tbenemy', mode='map', index='id', value_type='Enemy' },
    { name='TbQuest', file='tbquest', mode='map', index='id', value_type='Quest' },
}

local function InitTypes(methods)
    local readList = methods.readList
    local readArray = methods.readArray or readList
    local readSet = methods.readSet
    local readMap = methods.readMap

    local beans = {}
    do
        local class = methods.getClass('AIBehavior')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "MeleeAttack" then
                return beans["MeleeAttack"]._deserialize(bs)
elseif __type__ == "RangedAttack" then
                return beans["RangedAttack"]._deserialize(bs)
elseif __type__ == "PatrolMovement" then
                return beans["PatrolMovement"]._deserialize(bs)
elseif __type__ == "ChaseMovement" then
                return beans["ChaseMovement"]._deserialize(bs)
elseif __type__ == "DefenseBehavior" then
                return beans["DefenseBehavior"]._deserialize(bs)
            else
                error("Unknown type for AIBehavior: " .. tostring(__type__))
            end
        end
        beans['AIBehavior'] = class
    end
    do
        local class = methods.getClass('CombatBehavior')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "MeleeAttack" then
                return beans["MeleeAttack"]._deserialize(bs)
elseif __type__ == "RangedAttack" then
                return beans["RangedAttack"]._deserialize(bs)
            else
                error("Unknown type for CombatBehavior: " .. tostring(__type__))
            end
        end
        beans['CombatBehavior'] = class
    end
    do
        local class = methods.getClass('MeleeAttack')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['MeleeAttack'] = class
    end
    do
        local class = methods.getClass('RangedAttack')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['RangedAttack'] = class
    end
    do
        local class = methods.getClass('DefenseBehavior')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['DefenseBehavior'] = class
    end
    do
        local class = methods.getClass('MovementBehavior')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "PatrolMovement" then
                return beans["PatrolMovement"]._deserialize(bs)
elseif __type__ == "ChaseMovement" then
                return beans["ChaseMovement"]._deserialize(bs)
            else
                error("Unknown type for MovementBehavior: " .. tostring(__type__))
            end
        end
        beans['MovementBehavior'] = class
    end
    do
        local class = methods.getClass('ChaseMovement')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['ChaseMovement'] = class
    end
    do
        local class = methods.getClass('PatrolMovement')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['PatrolMovement'] = class
    end
    do
        local class = methods.getClass('Enemy')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.behaviors = readArray(bs.behaviors, beans['AIBehavior']._deserialize)
            o.dropRewards = readArray(bs.dropRewards, beans['Reward']._deserialize)
            setmetatable(o, class)
            return o
        end
        beans['Enemy'] = class
    end
    do
        local class = methods.getClass('Quest')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.rewards = readArray(bs.rewards, beans['Reward']._deserialize)
            setmetatable(o, class)
            return o
        end
        beans['Quest'] = class
    end
    do
        local class = methods.getClass('Reward')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "CurrencyReward" then
                return beans["CurrencyReward"]._deserialize(bs)
elseif __type__ == "ItemReward" then
                return beans["ItemReward"]._deserialize(bs)
elseif __type__ == "ExpReward" then
                return beans["ExpReward"]._deserialize(bs)
            else
                error("Unknown type for Reward: " .. tostring(__type__))
            end
        end
        beans['Reward'] = class
    end
    do
        local class = methods.getClass('CurrencyReward')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['CurrencyReward'] = class
    end
    do
        local class = methods.getClass('ExpReward')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['ExpReward'] = class
    end
    do
        local class = methods.getClass('ItemReward')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['ItemReward'] = class
    end
    do
        local class = methods.getClass('Skill')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.effect = beans['SkillEffect']._deserialize(bs.effect)
            setmetatable(o, class)
            return o
        end
        beans['Skill'] = class
    end
    do
        local class = methods.getClass('SkillEffect')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "DamageEffect" then
                return beans["DamageEffect"]._deserialize(bs)
elseif __type__ == "HealEffect" then
                return beans["HealEffect"]._deserialize(bs)
elseif __type__ == "BuffEffect" then
                return beans["BuffEffect"]._deserialize(bs)
            else
                error("Unknown type for SkillEffect: " .. tostring(__type__))
            end
        end
        beans['SkillEffect'] = class
    end
    do
        local class = methods.getClass('BuffEffect')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['BuffEffect'] = class
    end
    do
        local class = methods.getClass('DamageEffect')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['DamageEffect'] = class
    end
    do
        local class = methods.getClass('HealEffect')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['HealEffect'] = class
    end


    return { enums = enums, beans = beans, tables = tables }
    end

return { InitTypes = InitTypes }


