
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local setmetatable = setmetatable
local pairs = pairs
local tinsert = table.insert

local function get_map_size(m)
    local n = 0
    for _ in pairs(m) do
        n = n + 1
    end
    return n
end

local enums =
{
}

local tables =
{
    { name='TbEffectConfig', file='tbeffectconfig', mode='map', index='effectId', value_type='EffectConfig' },
}

local function InitTypes(methods)
    local readList = methods.readList
    local readArray = methods.readArray or readList
    local readSet = methods.readSet
    local readMap = methods.readMap

    local beans = {}
    do
        local class = methods.getClass('BaseTrigger')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "DamageTrigger" then
                return beans["DamageTrigger"]._deserialize(bs)
elseif __type__ == "HealTrigger" then
                return beans["HealTrigger"]._deserialize(bs)
elseif __type__ == "BuffTrigger" then
                return beans["BuffTrigger"]._deserialize(bs)
            else
                error("Unknown type for BaseTrigger: " .. tostring(__type__))
            end
        end
        beans['BaseTrigger'] = class
    end
    do
        local class = methods.getClass('BuffTrigger')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['BuffTrigger'] = class
    end
    do
        local class = methods.getClass('DamageTrigger')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['DamageTrigger'] = class
    end
    do
        local class = methods.getClass('HealTrigger')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['HealTrigger'] = class
    end
    do
        local class = methods.getClass('EffectConfig')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.triggerType = methods.getClass(bs.triggerType)
            setmetatable(o, class)
            return o
        end
        beans['EffectConfig'] = class
    end


    return { enums = enums, beans = beans, tables = tables }
    end

return { InitTypes = InitTypes }


