
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local setmetatable = setmetatable
local pairs = pairs
local ipairs = ipairs
local tinsert = table.insert

local function SimpleClass()
    local class = {}
    class.__index = class
    class.New = function(...)
        local ctor = class.ctor
        local o = ctor and ctor(...) or {}
        setmetatable(o, class)
        return o
    end
    return class
end


local function get_map_size(m)
    local n = 0
    for _ in pairs(m) do
        n = n + 1
    end
    return n
end

local enums =
{
    ---@class ItemRarity
     ---@field public Common integer
     ---@field public Rare integer
     ---@field public Epic integer
    ['ItemRarity'] = {   Common=1,  Rare=2,  Epic=3,  };
    ---@class ItemType
     ---@field public Weapon string
     ---@field public Armor string
     ---@field public Consumable string
    ['ItemType'] = {   Weapon='weapon',  Armor='armor',  Consumable='consumable',  };
}

local tables =
{
    { name='TbItem', file='tbitem', mode='map', index='id', value_type='Item' },
}

local function InitTypes(methods)
    local readBool = methods.readBool
    local readByte = methods.readByte
    local readShort = methods.readShort
    local readFshort = methods.readFshort
    local readInt = methods.readInt
    local readFint = methods.readFint
    local readLong = methods.readLong
    local readFlong = methods.readFlong
    local readFloat = methods.readFloat
    local readDouble = methods.readDouble
    local readSize = methods.readSize

    local readString = methods.readString

    local function readList(bs, keyFun)
        local list = {}
        local v
        for i = 1, readSize(bs) do
            tinsert(list, keyFun(bs))
        end
        return list
    end

    local readArray = readList

    local function readSet(bs, keyFun)
        local set = {}
        local v
        for i = 1, readSize(bs) do
            tinsert(set, keyFun(bs))
        end
        return set
    end

    local function readMap(bs, keyFun, valueFun)
        local map = {}
        for i = 1, readSize(bs) do
            local k = keyFun(bs)
            local v = valueFun(bs)
            map[k] = v
        end
        return map
    end

    local function readNullableBool(bs)
        if readBool(bs) then
            return readBool(bs)
        end
    end

    local beans = {}
        do
        ---@class Item
         ---@field public id integer
         ---@field public name string
         ---@field public type integer
         ---@field public rarity integer

            local class = {
                { name='id', type='integer'},
                { name='name', type='string'},
                { name='type', type='integer'},
                { name='rarity', type='integer'},
            }
            beans['Item'] = class
        end

    local beans = {}
    do
    ---@class Item
         ---@field public id integer
         ---@field public name string
         ---@field public type integer
         ---@field public rarity integer

        local class = SimpleClass()
        class._id = 2289459
        class._type_ = 'Item'
        local id2name = {  }
        class._deserialize = function(bs)
            local o = {
            id = readInt(bs),
            name = readString(bs),
            type = readInt(bs),
            rarity = readInt(bs),
            }
            setmetatable(o, class)
            return o
        end
        beans[class._type_] = class
    end


    return { enums = enums, beans = beans, tables = tables }
    end

return { InitTypes = InitTypes }


