
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local setmetatable = setmetatable
local pairs = pairs
local tinsert = table.insert

local function get_map_size(m)
    local n = 0
    for _ in pairs(m) do
        n = n + 1
    end
    return n
end

local enums =
{
}

local tables =
{
    { name='TbItem', file='tbitem', mode='map', index='id', value_type='Item' },
    { name='TbEntity', file='tbentity', mode='map', index='id', value_type='Entity' },
    { name='TbPath', file='tbpath', mode='map', index='id', value_type='Path' },
    { name='TbSpawner', file='tbspawner', mode='map', index='id', value_type='Spawner' },
    { name='TbMixedSpawner', file='tbmixedspawner', mode='map', index='id', value_type='MixedSpawner' },
}

local function InitTypes(methods)
    local readList = methods.readList
    local readArray = methods.readArray or readList
    local readSet = methods.readSet
    local readMap = methods.readMap

    local beans = {}
    do
        local class = methods.getClass('CFrame')
        class._deserialize = function(bs)
            if not bs then return nil end
            return CFrame.new(Vector3.new(bs.Position.X, bs.Position.Y, bs.Position.Z), Vector3.new(bs.LookVector.X, bs.LookVector.Y, bs.LookVector.Z))
        end
        beans['CFrame'] = class
    end
    do
        local class = methods.getClass('Color3')
        class._deserialize = function(bs)
            if not bs then return nil end
            return Color3.new(bs.R, bs.G, bs.B)
        end
        beans['Color3'] = class
    end
    do
        local class = methods.getClass('Entity')
        class._deserialize = function(bs)
            if not bs then return nil end
            local o = table.clone(bs)
            o.transform = CFrame.new(Vector3.new(bs.transform.Position.X, bs.transform.Position.Y, bs.transform.Position.Z), Vector3.new(bs.transform.LookVector.X, bs.transform.LookVector.Y, bs.transform.LookVector.Z))
            setmetatable(o, class)
            return o
        end
        beans['Entity'] = class
    end
    do
        local class = methods.getClass('Item')
        class._deserialize = function(bs)
            if not bs then return nil end
            local o = table.clone(bs)
            o.position = Vector3.new(bs.position.X, bs.position.Y, bs.position.Z)
            o.color = Color3.new(bs.color.R, bs.color.G, bs.color.B)
            setmetatable(o, class)
            return o
        end
        beans['Item'] = class
    end
    do
        local class = methods.getClass('MixedSpawner')
        class._deserialize = function(bs)
            if not bs then return nil end
            local o = table.clone(bs)
            o.spawnOffset = CFrame.new(Vector3.new(bs.spawnOffset.Position.X, bs.spawnOffset.Position.Y, bs.spawnOffset.Position.Z), Vector3.new(bs.spawnOffset.LookVector.X, bs.spawnOffset.LookVector.Y, bs.spawnOffset.LookVector.Z))
            o.spawnPosition = (bs.spawnPosition and Vector3.new(bs.spawnPosition.X, bs.spawnPosition.Y, bs.spawnPosition.Z) or nil)
            setmetatable(o, class)
            return o
        end
        beans['MixedSpawner'] = class
    end
    do
        local class = methods.getClass('Path')
        class._deserialize = function(bs)
            if not bs then return nil end
            local o = table.clone(bs)
            o.waypoints = readList(bs.waypoints, beans['Vector3']._deserialize)
            setmetatable(o, class)
            return o
        end
        beans['Path'] = class
    end
    do
        local class = methods.getClass('Spawner')
        class._deserialize = function(bs)
            if not bs then return nil end
            local o = table.clone(bs)
            o.spawnPosition = (bs.spawnPosition and CFrame.new(Vector3.new(bs.spawnPosition.Position.X, bs.spawnPosition.Position.Y, bs.spawnPosition.Position.Z), Vector3.new(bs.spawnPosition.LookVector.X, bs.spawnPosition.LookVector.Y, bs.spawnPosition.LookVector.Z)) or nil)
            o.targetPosition = (bs.targetPosition and Vector3.new(bs.targetPosition.X, bs.targetPosition.Y, bs.targetPosition.Z) or nil)
            o.highlightColor = (bs.highlightColor and Color3.new(bs.highlightColor.R, bs.highlightColor.G, bs.highlightColor.B) or nil)
            setmetatable(o, class)
            return o
        end
        beans['Spawner'] = class
    end
    do
        local class = methods.getClass('Vector2')
        class._deserialize = function(bs)
            if not bs then return nil end
            return Vector2.new(bs.X, bs.Y)
        end
        beans['Vector2'] = class
    end
    do
        local class = methods.getClass('Vector3')
        class._deserialize = function(bs)
            if not bs then return nil end
            return Vector3.new(bs.X, bs.Y, bs.Z)
        end
        beans['Vector3'] = class
    end


    return { enums = enums, beans = beans, tables = tables }
    end

return { InitTypes = InitTypes }


